#!/bin/sh
# LinksPage backups (docs/tech-selection.md §12.5).
#   linkspage-backup once   run one backup and exit (non-zero on any failure)
#   linkspage-backup loop   back up daily (default)
#
# Every artifact is streamed (through age when BACKUP_AGE_RECIPIENT is
# set) into a .part file and only renamed once the whole pipeline
# succeeded, so plaintext never touches disk when encrypting and a failed
# run never publishes a truncated backup. Old backups are pruned only
# after every artifact of the run succeeded.
set -eu
# pipefail is POSIX.1-2024 and supported by busybox ash (the image's sh).
# shellcheck disable=SC3040
set -o pipefail
umask 077

BACKUP_DIR=${BACKUP_DIR:-/backups}
KEEP_DAYS=${BACKUP_KEEP_DAYS:-14}
OWNER_UID=${BACKUP_UID:-1000}
RECIPIENT=${BACKUP_AGE_RECIPIENT:-}
INTERVAL=${BACKUP_INTERVAL_SECONDS:-86400}
SRC_DIR=${BACKUP_SRC_DIR:-/src}
DATA_DIR=${BACKUP_DATA_DIR:-/data}
PG_PASSWORD_FILE=${BACKUP_PG_PASSWORD_FILE:-/run/secrets/pg_password}

log() { printf '%s backup: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
die() { log "ERROR: $*" >&2; exit 1; }

# encrypt: stdin -> stdout, through age when a recipient is configured.
encrypt() {
  if [ -n "$RECIPIENT" ]; then
    age -r "$RECIPIENT"
  else
    cat
  fi
}

# final_name NAME: published file name for an artifact.
final_name() {
  if [ -n "$RECIPIENT" ]; then
    printf '%s/%s.age' "$BACKUP_DIR" "$1"
  else
    printf '%s/%s' "$BACKUP_DIR" "$1"
  fi
}

# publish NAME: atomically rename NAME's .part file after checking it.
publish() {
  out=$(final_name "$1")
  [ -s "$out.part" ] || die "$1: empty output"
  chown "$OWNER_UID" "$out.part"
  mv "$out.part" "$out"
  log "wrote ${out##*/}"
}

check_recipient() {
  [ -n "$RECIPIENT" ] || return 0
  age -r "$RECIPIENT" </dev/null >/dev/null 2>&1 || die "BACKUP_AGE_RECIPIENT is not a valid age recipient"
}

run_once() {
  check_recipient
  PGPASSWORD=$(cat "$PG_PASSWORD_FILE") || die "cannot read $PG_PASSWORD_FILE"
  export PGPASSWORD PGHOST="${PGHOST:-db}" PGUSER="${PGUSER:-linkspage}" PGDATABASE="${PGDATABASE:-linkspage}"
  stamp=$(date -u +%Y%m%dT%H%M%SZ)
  mkdir -p "$BACKUP_DIR"
  trap 'rm -f "$BACKUP_DIR"/*.part' EXIT
  trap 'exit 1' INT TERM

  log "dumping database"
  name="db-$stamp.dump"
  pg_dump -Fc --exclude-table-data=analytics_salt | encrypt > "$(final_name "$name").part"
  publish "$name"

  if [ -d "$DATA_DIR/uploads" ]; then
    name="uploads-$stamp.tar"
    tar -C "$DATA_DIR" -cf - uploads | encrypt > "$(final_name "$name").part"
    publish "$name"
  fi

  # The secret key, admin hashes and config are only ever stored encrypted.
  if [ -z "$RECIPIENT" ]; then
    log "WARN: BACKUP_AGE_RECIPIENT is not set; .secret_key, config/ and admin hashes are skipped, back them up encrypted yourself"
  else
    if [ -f "$DATA_DIR/.secret_key" ]; then
      name="secret-key-$stamp.tar"
      tar -C "$DATA_DIR" -cf - .secret_key | encrypt > "$(final_name "$name").part"
      publish "$name"
    fi
    # Only what a restore needs: config/ and the admin password hashes
    # (pg_password and tunnel_token are regenerated by init.sh).
    set -- config
    for f in "$SRC_DIR"/secrets/admin_*; do
      if [ -e "$f" ]; then set -- "$@" "secrets/${f##*/}"; fi
    done
    name="config-$stamp.tar"
    tar -C "$SRC_DIR" -cf - "$@" | encrypt > "$(final_name "$name").part"
    publish "$name"
  fi

  find "$BACKUP_DIR" -maxdepth 1 -type f -mtime +"$KEEP_DAYS" \
    \( -name 'db-*' -o -name 'uploads-*' -o -name 'secret-key-*' -o -name 'config-*' \) -exec rm -f {} +
  log "done ($stamp)"
}

case "${1:-loop}" in
  once) run_once ;;
  loop)
    while :; do
      # A separate process per run keeps `set -e` effective inside it.
      "$0" once || log "ERROR: backup failed"
      sleep "$INTERVAL"
    done
    ;;
  *) printf 'usage: %s once|loop\n' "$0" >&2; exit 2 ;;
esac
