// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertBlock = `-- name: InsertBlock :one
INSERT INTO page_blocks (page_id, kind, community_id, link_id, data, sort_order, visible, visible_from, visible_to)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertBlockParams struct {
	PageID      int16
	Kind        string
	CommunityID pgtype.UUID
	LinkID      pgtype.UUID
	Data        []byte
	SortOrder   int32
	Visible     bool
	VisibleFrom pgtype.Timestamptz
	VisibleTo   pgtype.Timestamptz
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertBlock,
		arg.PageID,
		arg.Kind,
		arg.CommunityID,
		arg.LinkID,
		arg.Data,
		arg.SortOrder,
		arg.Visible,
		arg.VisibleFrom,
		arg.VisibleTo,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listVisibleBlocks = `-- name: ListVisibleBlocks :many
SELECT id, page_id, kind, community_id, link_id, data, sort_order, visible, visible_from, visible_to
FROM page_blocks
WHERE page_id = $1
  AND visible
  AND (visible_from IS NULL OR visible_from <= $2::timestamptz)
  AND (visible_to IS NULL OR visible_to > $2::timestamptz)
ORDER BY sort_order, id
`

type ListVisibleBlocksParams struct {
	PageID int16
	Now    pgtype.Timestamptz
}

type ListVisibleBlocksRow struct {
	ID          pgtype.UUID
	PageID      int16
	Kind        string
	CommunityID pgtype.UUID
	LinkID      pgtype.UUID
	Data        []byte
	SortOrder   int32
	Visible     bool
	VisibleFrom pgtype.Timestamptz
	VisibleTo   pgtype.Timestamptz
}

// Blocks visible at @now, in display order.
func (q *Queries) ListVisibleBlocks(ctx context.Context, arg ListVisibleBlocksParams) ([]ListVisibleBlocksRow, error) {
	rows, err := q.db.Query(ctx, listVisibleBlocks, arg.PageID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleBlocksRow{}
	for rows.Next() {
		var i ListVisibleBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Kind,
			&i.CommunityID,
			&i.LinkID,
			&i.Data,
			&i.SortOrder,
			&i.Visible,
			&i.VisibleFrom,
			&i.VisibleTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBlockBoundary = `-- name: NextBlockBoundary :one
SELECT min(b)::timestamptz AS next_boundary
FROM (
    SELECT f.visible_from AS b FROM page_blocks f
    WHERE f.page_id = $1::smallint AND f.visible AND f.visible_from > $2::timestamptz
    UNION ALL
    SELECT t.visible_to AS b FROM page_blocks t
    WHERE t.page_id = $1::smallint AND t.visible AND t.visible_to > $2::timestamptz
) AS boundaries
`

type NextBlockBoundaryParams struct {
	PageID int16
	Now    pgtype.Timestamptz
}

// The earliest future visible_from/visible_to after @now (NULL when none):
// the public page must be rebuilt when it is reached (doc 4.6).
func (q *Queries) NextBlockBoundary(ctx context.Context, arg NextBlockBoundaryParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextBlockBoundary, arg.PageID, arg.Now)
	var next_boundary pgtype.Timestamptz
	err := row.Scan(&next_boundary)
	return next_boundary, err
}
