// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communities.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommunityBySlug = `-- name: GetCommunityBySlug :one
SELECT id, page_id, slug, provider, platform, external_id, config, display, icon_key,
       invite_url, fallback_url, refresh_interval, created_at, updated_at
FROM communities
WHERE slug = $1
`

func (q *Queries) GetCommunityBySlug(ctx context.Context, slug string) (Community, error) {
	row := q.db.QueryRow(ctx, getCommunityBySlug, slug)
	var i Community
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Slug,
		&i.Provider,
		&i.Platform,
		&i.ExternalID,
		&i.Config,
		&i.Display,
		&i.IconKey,
		&i.InviteUrl,
		&i.FallbackUrl,
		&i.RefreshInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoCommunity = `-- name: GetGoCommunity :one
SELECT c.id, c.slug, c.provider, c.platform, c.display, c.invite_url, c.fallback_url,
       s.state AS snapshot_state, s.err_code AS snapshot_err_code, s.data AS snapshot_data,
       q.id AS qr_id
FROM communities c
LEFT JOIN provider_snapshots s ON s.community_id = c.id
LEFT JOIN community_qr_codes q ON q.community_id = c.id
WHERE c.slug = $1
  AND EXISTS (
      SELECT 1 FROM page_blocks b
      WHERE b.page_id = c.page_id
        AND b.community_id = c.id
        AND b.visible
        AND (b.visible_from IS NULL OR b.visible_from <= now())
        AND (b.visible_to IS NULL OR b.visible_to > now())
  )
`

type GetGoCommunityRow struct {
	ID              pgtype.UUID
	Slug            string
	Provider        string
	Platform        string
	Display         []byte
	InviteUrl       *string
	FallbackUrl     *string
	SnapshotState   *string
	SnapshotErrCode *string
	SnapshotData    []byte
	QrID            pgtype.UUID
}

// Everything /go/{slug} needs to pick a target for a community (doc 5.6).
// Only communities published on the page right now: hidden, scheduled,
// expired or unplaced ones resolve like unknown slugs.
func (q *Queries) GetGoCommunity(ctx context.Context, slug string) (GetGoCommunityRow, error) {
	row := q.db.QueryRow(ctx, getGoCommunity, slug)
	var i GetGoCommunityRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Provider,
		&i.Platform,
		&i.Display,
		&i.InviteUrl,
		&i.FallbackUrl,
		&i.SnapshotState,
		&i.SnapshotErrCode,
		&i.SnapshotData,
		&i.QrID,
	)
	return i, err
}

const insertCommunity = `-- name: InsertCommunity :one
INSERT INTO communities (page_id, slug, provider, platform, external_id, config, display, icon_key,
                         invite_url, fallback_url, refresh_interval)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11)
RETURNING id
`

type InsertCommunityParams struct {
	PageID          int16
	Slug            string
	Provider        string
	Platform        string
	ExternalID      *string
	Config          []byte
	Display         []byte
	IconKey         *string
	InviteUrl       *string
	FallbackUrl     *string
	RefreshInterval pgtype.Interval
}

func (q *Queries) InsertCommunity(ctx context.Context, arg InsertCommunityParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCommunity,
		arg.PageID,
		arg.Slug,
		arg.Provider,
		arg.Platform,
		arg.ExternalID,
		arg.Config,
		arg.Display,
		arg.IconKey,
		arg.InviteUrl,
		arg.FallbackUrl,
		arg.RefreshInterval,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listCommunities = `-- name: ListCommunities :many
SELECT id, page_id, slug, provider, platform, external_id, config, display, icon_key,
       invite_url, fallback_url, refresh_interval, created_at, updated_at
FROM communities
WHERE page_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListCommunities(ctx context.Context, pageID int16) ([]Community, error) {
	rows, err := q.db.Query(ctx, listCommunities, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Community{}
	for rows.Next() {
		var i Community
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Slug,
			&i.Provider,
			&i.Platform,
			&i.ExternalID,
			&i.Config,
			&i.Display,
			&i.IconKey,
			&i.InviteUrl,
			&i.FallbackUrl,
			&i.RefreshInterval,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCommunities = `-- name: ListDueCommunities :many
SELECT c.id, c.slug, c.provider, c.external_id, c.config, c.invite_url, c.refresh_interval,
       s.fail_count AS fail_count, s.last_ok_at AS last_ok_at
FROM communities c
LEFT JOIN provider_snapshots s ON s.community_id = c.id
WHERE c.provider <> 'static'
  AND (s.next_fetch_at IS NULL OR s.next_fetch_at <= $1::timestamptz)
ORDER BY s.next_fetch_at NULLS FIRST, c.id
LIMIT $2
`

type ListDueCommunitiesParams struct {
	Now     pgtype.Timestamptz
	MaxRows int32
}

type ListDueCommunitiesRow struct {
	ID              pgtype.UUID
	Slug            string
	Provider        string
	ExternalID      *string
	Config          []byte
	InviteUrl       *string
	RefreshInterval pgtype.Interval
	FailCount       *int32
	LastOkAt        pgtype.Timestamptz
}

// Provider-backed communities whose next fetch is due (or that were never
// fetched), most overdue first.
func (q *Queries) ListDueCommunities(ctx context.Context, arg ListDueCommunitiesParams) ([]ListDueCommunitiesRow, error) {
	rows, err := q.db.Query(ctx, listDueCommunities, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueCommunitiesRow{}
	for rows.Next() {
		var i ListDueCommunitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Provider,
			&i.ExternalID,
			&i.Config,
			&i.InviteUrl,
			&i.RefreshInterval,
			&i.FailCount,
			&i.LastOkAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
