// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGoLink = `-- name: GetGoLink :one
SELECT l.id, l.slug, l.url
FROM links l
WHERE l.slug = $1
  AND EXISTS (
      SELECT 1 FROM page_blocks b
      WHERE b.page_id = l.page_id
        AND b.visible
        AND (b.visible_from IS NULL OR b.visible_from <= now())
        AND (b.visible_to IS NULL OR b.visible_to > now())
        AND (b.link_id = l.id
             OR (b.kind = 'social_row' AND b.data -> 'linkIds' @> jsonb_build_array(l.id::text)))
  )
`

type GetGoLinkRow struct {
	ID   pgtype.UUID
	Slug string
	Url  string
}

// The /go/{slug} target of a link published on the page right now (a
// visible link block, or a visible social_row listing it); hidden,
// scheduled, expired or unplaced links resolve like unknown slugs.
func (q *Queries) GetGoLink(ctx context.Context, slug string) (GetGoLinkRow, error) {
	row := q.db.QueryRow(ctx, getGoLink, slug)
	var i GetGoLinkRow
	err := row.Scan(&i.ID, &i.Slug, &i.Url)
	return i, err
}

const getLinkBySlug = `-- name: GetLinkBySlug :one
SELECT id, page_id, slug, kind, label, url, icon, icon_key, rel_me, created_at, updated_at
FROM links
WHERE slug = $1
`

func (q *Queries) GetLinkBySlug(ctx context.Context, slug string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkBySlug, slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Slug,
		&i.Kind,
		&i.Label,
		&i.Url,
		&i.Icon,
		&i.IconKey,
		&i.RelMe,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLink = `-- name: InsertLink :one
INSERT INTO links (page_id, slug, kind, label, url, icon, icon_key, rel_me)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertLinkParams struct {
	PageID  int16
	Slug    string
	Kind    string
	Label   []byte
	Url     string
	Icon    *string
	IconKey *string
	RelMe   bool
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertLink,
		arg.PageID,
		arg.Slug,
		arg.Kind,
		arg.Label,
		arg.Url,
		arg.Icon,
		arg.IconKey,
		arg.RelMe,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, page_id, slug, kind, label, url, icon, icon_key, rel_me, created_at, updated_at
FROM links
WHERE page_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListLinks(ctx context.Context, pageID int16) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Slug,
			&i.Kind,
			&i.Label,
			&i.Url,
			&i.Icon,
			&i.IconKey,
			&i.RelMe,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
