// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_proxy.sql

package dbq

import (
	"context"
)

const getMediaProxy = `-- name: GetMediaProxy :one
SELECT key, provider, url, ext, kind, created_at, last_seen_at
FROM media_proxy
WHERE key = $1
`

func (q *Queries) GetMediaProxy(ctx context.Context, key string) (MediaProxy, error) {
	row := q.db.QueryRow(ctx, getMediaProxy, key)
	var i MediaProxy
	err := row.Scan(
		&i.Key,
		&i.Provider,
		&i.Url,
		&i.Ext,
		&i.Kind,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchMediaProxy = `-- name: TouchMediaProxy :exec
UPDATE media_proxy SET last_seen_at = now()
WHERE key = ANY($1::text[])
`

func (q *Queries) TouchMediaProxy(ctx context.Context, keys []string) error {
	_, err := q.db.Exec(ctx, touchMediaProxy, keys)
	return err
}

const upsertMediaProxy = `-- name: UpsertMediaProxy :exec
INSERT INTO media_proxy (key, provider, url, ext, kind)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (key) DO UPDATE SET last_seen_at = now()
`

type UpsertMediaProxyParams struct {
	Key      string
	Provider string
	Url      string
	Ext      string
	Kind     string
}

// Registers an upstream URL; re-registering refreshes last_seen_at.
func (q *Queries) UpsertMediaProxy(ctx context.Context, arg UpsertMediaProxyParams) error {
	_, err := q.db.Exec(ctx, upsertMediaProxy,
		arg.Key,
		arg.Provider,
		arg.Url,
		arg.Ext,
		arg.Kind,
	)
	return err
}
