// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package dbq

import (
	"context"
)

const getMedia = `-- name: GetMedia :one
SELECT key, kind, content_type, bytes, width, height, variants, created_at, created_by
FROM media
WHERE key = $1
`

func (q *Queries) GetMedia(ctx context.Context, key string) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, key)
	var i Medium
	err := row.Scan(
		&i.Key,
		&i.Kind,
		&i.ContentType,
		&i.Bytes,
		&i.Width,
		&i.Height,
		&i.Variants,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertMedia = `-- name: InsertMedia :exec
INSERT INTO media (key, kind, content_type, bytes, width, height, variants, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (key) DO NOTHING
`

type InsertMediaParams struct {
	Key         string
	Kind        string
	ContentType string
	Bytes       int32
	Width       int32
	Height      int32
	Variants    []byte
	CreatedBy   *string
}

// Content-addressed: inserting the same key twice is a no-op.
func (q *Queries) InsertMedia(ctx context.Context, arg InsertMediaParams) error {
	_, err := q.db.Exec(ctx, insertMedia,
		arg.Key,
		arg.Kind,
		arg.ContentType,
		arg.Bytes,
		arg.Width,
		arg.Height,
		arg.Variants,
		arg.CreatedBy,
	)
	return err
}

const listMediaByKeys = `-- name: ListMediaByKeys :many
SELECT key, kind, content_type, bytes, width, height, variants, created_at, created_by
FROM media
WHERE key = ANY($1::text[])
`

func (q *Queries) ListMediaByKeys(ctx context.Context, keys []string) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByKeys, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.Key,
			&i.Kind,
			&i.ContentType,
			&i.Bytes,
			&i.Width,
			&i.Height,
			&i.Variants,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
