// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Page struct {
	ID   int16
	Slug string
}

type SchemaMetum struct {
	ID                      bool
	MinCompatibleAppVersion string
}

type SiteSetting struct {
	PageID    int16
	Version   int64
	Data      []byte
	UpdatedAt pgtype.Timestamptz
	UpdatedBy *string
}
