// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platforms.sql

package dbq

import (
	"context"
)

const insertCustomPlatform = `-- name: InsertCustomPlatform :exec
INSERT INTO custom_platforms (id, name, icon, icon_key, url_pattern, needs_external_browser)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCustomPlatformParams struct {
	ID                   string
	Name                 []byte
	Icon                 *string
	IconKey              *string
	UrlPattern           *string
	NeedsExternalBrowser bool
}

func (q *Queries) InsertCustomPlatform(ctx context.Context, arg InsertCustomPlatformParams) error {
	_, err := q.db.Exec(ctx, insertCustomPlatform,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.IconKey,
		arg.UrlPattern,
		arg.NeedsExternalBrowser,
	)
	return err
}

const listCustomPlatforms = `-- name: ListCustomPlatforms :many
SELECT id, name, icon, icon_key, url_pattern, needs_external_browser, created_at, updated_at
FROM custom_platforms
ORDER BY id
`

func (q *Queries) ListCustomPlatforms(ctx context.Context) ([]CustomPlatform, error) {
	rows, err := q.db.Query(ctx, listCustomPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomPlatform{}
	for rows.Next() {
		var i CustomPlatform
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.IconKey,
			&i.UrlPattern,
			&i.NeedsExternalBrowser,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
