// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qr.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQRCode = `-- name: GetQRCode :one
SELECT q.id, q.community_id, q.media_key, q.note, q.updated_at,
       m.content_type, m.bytes, m.width, m.height
FROM community_qr_codes q
JOIN media m ON m.key = q.media_key
WHERE q.id = $1
`

type GetQRCodeRow struct {
	ID          pgtype.UUID
	CommunityID pgtype.UUID
	MediaKey    string
	Note        []byte
	UpdatedAt   pgtype.Timestamptz
	ContentType string
	Bytes       int32
	Width       int32
	Height      int32
}

// Served by /media/q/{id}; a missing id means replaced or deleted (410).
func (q *Queries) GetQRCode(ctx context.Context, id pgtype.UUID) (GetQRCodeRow, error) {
	row := q.db.QueryRow(ctx, getQRCode, id)
	var i GetQRCodeRow
	err := row.Scan(
		&i.ID,
		&i.CommunityID,
		&i.MediaKey,
		&i.Note,
		&i.UpdatedAt,
		&i.ContentType,
		&i.Bytes,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const insertQRCode = `-- name: InsertQRCode :one
INSERT INTO community_qr_codes (community_id, media_key, note)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertQRCodeParams struct {
	CommunityID pgtype.UUID
	MediaKey    string
	Note        []byte
}

func (q *Queries) InsertQRCode(ctx context.Context, arg InsertQRCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertQRCode, arg.CommunityID, arg.MediaKey, arg.Note)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listQRCodes = `-- name: ListQRCodes :many
SELECT q.id, q.community_id, q.media_key, q.note, q.updated_at,
       m.content_type, m.width, m.height
FROM community_qr_codes q
JOIN communities c ON c.id = q.community_id
JOIN media m ON m.key = q.media_key
WHERE c.page_id = $1
`

type ListQRCodesRow struct {
	ID          pgtype.UUID
	CommunityID pgtype.UUID
	MediaKey    string
	Note        []byte
	UpdatedAt   pgtype.Timestamptz
	ContentType string
	Width       int32
	Height      int32
}

func (q *Queries) ListQRCodes(ctx context.Context, pageID int16) ([]ListQRCodesRow, error) {
	rows, err := q.db.Query(ctx, listQRCodes, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQRCodesRow{}
	for rows.Next() {
		var i ListQRCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.CommunityID,
			&i.MediaKey,
			&i.Note,
			&i.UpdatedAt,
			&i.ContentType,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
