// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package dbq

import (
	"context"
)

const isContentEmpty = `-- name: IsContentEmpty :one
SELECT (
    NOT EXISTS (SELECT 1 FROM page_blocks)
    AND NOT EXISTS (SELECT 1 FROM communities)
    AND NOT EXISTS (SELECT 1 FROM links)
)::boolean AS empty
`

// Seeding only runs on an empty page (no blocks, communities or links).
func (q *Queries) IsContentEmpty(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, isContentEmpty)
	var empty bool
	err := row.Scan(&empty)
	return empty, err
}

const replaceSiteSettingsData = `-- name: ReplaceSiteSettingsData :one
UPDATE site_settings
SET data = $1, version = version + 1, updated_at = now(), updated_by = $2
WHERE page_id = $3
RETURNING version
`

type ReplaceSiteSettingsDataParams struct {
	Data      []byte
	UpdatedBy *string
	PageID    int16
}

// Writes seeded settings and bumps the version.
func (q *Queries) ReplaceSiteSettingsData(ctx context.Context, arg ReplaceSiteSettingsDataParams) (int64, error) {
	row := q.db.QueryRow(ctx, replaceSiteSettingsData, arg.Data, arg.UpdatedBy, arg.PageID)
	var version int64
	err := row.Scan(&version)
	return version, err
}
