// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site.sql

package dbq

import (
	"context"
)

const getDefaultPage = `-- name: GetDefaultPage :one
SELECT id, slug
FROM pages
WHERE id = 1
`

func (q *Queries) GetDefaultPage(ctx context.Context) (Page, error) {
	row := q.db.QueryRow(ctx, getDefaultPage)
	var i Page
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const getMinCompatibleAppVersion = `-- name: GetMinCompatibleAppVersion :one
SELECT min_compatible_app_version
FROM schema_meta
WHERE id
`

func (q *Queries) GetMinCompatibleAppVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getMinCompatibleAppVersion)
	var min_compatible_app_version string
	err := row.Scan(&min_compatible_app_version)
	return min_compatible_app_version, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, slug
FROM pages
WHERE slug = $1
`

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageBySlug, slug)
	var i Page
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT page_id, version, data, updated_at, updated_by
FROM site_settings
WHERE page_id = 1
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.PageID,
		&i.Version,
		&i.Data,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
