// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureProviderSnapshot = `-- name: EnsureProviderSnapshot :exec
INSERT INTO provider_snapshots (community_id, state, next_fetch_at)
VALUES ($1, 'pending', now())
ON CONFLICT (community_id) DO NOTHING
`

// Creates a pending row so a new community is fetched right away.
func (q *Queries) EnsureProviderSnapshot(ctx context.Context, communityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureProviderSnapshot, communityID)
	return err
}

const getProviderSnapshot = `-- name: GetProviderSnapshot :one
SELECT community_id, data, state, err_code, fetched_at, last_ok_at, next_fetch_at, fail_count
FROM provider_snapshots
WHERE community_id = $1
`

func (q *Queries) GetProviderSnapshot(ctx context.Context, communityID pgtype.UUID) (ProviderSnapshot, error) {
	row := q.db.QueryRow(ctx, getProviderSnapshot, communityID)
	var i ProviderSnapshot
	err := row.Scan(
		&i.CommunityID,
		&i.Data,
		&i.State,
		&i.ErrCode,
		&i.FetchedAt,
		&i.LastOkAt,
		&i.NextFetchAt,
		&i.FailCount,
	)
	return i, err
}

const listProviderSnapshots = `-- name: ListProviderSnapshots :many
SELECT s.community_id, s.data, s.state, s.err_code, s.fetched_at, s.last_ok_at, s.next_fetch_at, s.fail_count
FROM provider_snapshots s
JOIN communities c ON c.id = s.community_id
WHERE c.page_id = $1
`

func (q *Queries) ListProviderSnapshots(ctx context.Context, pageID int16) ([]ProviderSnapshot, error) {
	rows, err := q.db.Query(ctx, listProviderSnapshots, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderSnapshot{}
	for rows.Next() {
		var i ProviderSnapshot
		if err := rows.Scan(
			&i.CommunityID,
			&i.Data,
			&i.State,
			&i.ErrCode,
			&i.FetchedAt,
			&i.LastOkAt,
			&i.NextFetchAt,
			&i.FailCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProviderSnapshot = `-- name: UpsertProviderSnapshot :exec
INSERT INTO provider_snapshots (community_id, data, state, err_code, fetched_at, last_ok_at, next_fetch_at, fail_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (community_id) DO UPDATE SET
    data          = excluded.data,
    state         = excluded.state,
    err_code      = excluded.err_code,
    fetched_at    = excluded.fetched_at,
    last_ok_at    = excluded.last_ok_at,
    next_fetch_at = excluded.next_fetch_at,
    fail_count    = excluded.fail_count
`

type UpsertProviderSnapshotParams struct {
	CommunityID pgtype.UUID
	Data        []byte
	State       string
	ErrCode     *string
	FetchedAt   pgtype.Timestamptz
	LastOkAt    pgtype.Timestamptz
	NextFetchAt pgtype.Timestamptz
	FailCount   int32
}

func (q *Queries) UpsertProviderSnapshot(ctx context.Context, arg UpsertProviderSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertProviderSnapshot,
		arg.CommunityID,
		arg.Data,
		arg.State,
		arg.ErrCode,
		arg.FetchedAt,
		arg.LastOkAt,
		arg.NextFetchAt,
		arg.FailCount,
	)
	return err
}
